### ISSUE TITLE
Navigation bar icon issue

### ISSUE THREAD

**Issue by duskdev17** [duskdev17/portfolioApp#2]
Navbar icon on ios version of the app works fine like it shows an down arrow. But navbar icon isn't working on the android version of the app. 
![Screenshot_1710548699](https://github.com/duskdev17/portfolioApp/assets/65917000/73bf16b7-cee7-4c31-a484-a6e031ed509e)

**Comment by deathRayZ** [comment]
It can be fixed upon importing/ using bottom tab navigator module. 
Read docs: https://reactnavigation.org/docs/bottom-tab-navigator/
